# Generated by Django 5.2.5 on 2025-08-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('market_id', models.AutoField(primary_key=True, serialize=False)),
                ('market_name', models.CharField(max_length=40)),
                ('market_image', models.CharField(blank=True, max_length=255, null=True)),
                ('market_english', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'verbose_name': '시장',
                'verbose_name_plural': '시장 목록',
                'db_table': 'market',
            },
        ),
    ]
