# Generated by Django 5.2.5 on 2025-08-21 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='market_image2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='market',
            name='market_image3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
