# Generated by Django 5.2.5 on 2025-08-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_uid', models.CharField(db_index=True, max_length=128)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_time', models.TimeField(blank=True, null=True)),
                ('payment_datetime', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('store_name', models.CharField(blank=True, max_length=255, null=True)),
                ('store_biz_no', models.CharField(blank=True, max_length=64, null=True)),
                ('store_address', models.TextField(blank=True)),
                ('store_tels', models.JSONField(blank=True, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('currency', models.CharField(blank=True, default='KRW', max_length=8, null=True)),
                ('receipt_result_raw', models.JSONField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['image_uid'], name='receipts_re_image_u_baae1b_idx'), models.Index(fields=['payment_date'], name='receipts_re_payment_d6195a_idx'), models.Index(fields=['store_name'], name='receipts_re_store_n_49a500_idx')],
            },
        ),
    ]
