# Generated by Django 5.2.4 on 2025-08-22 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='store_biz_no',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='store_tels',
        ),
    ]
