# Generated by Django 5.2.4 on 2025-08-22 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rewardhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardhistory',
            name='balance',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
