# Generated by Django 5.2.4 on 2025-08-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reviewtag',
            name='unique_category_tag',
        ),
        migrations.AddField(
            model_name='reviewtag',
            name='group',
            field=models.CharField(default='Review Tags', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reviewtag',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AddIndex(
            model_name='reviewtag',
            index=models.Index(fields=['category', 'group'], name='reviews_rev_categor_8378aa_idx'),
        ),
        migrations.AddConstraint(
            model_name='reviewtag',
            constraint=models.UniqueConstraint(fields=('category', 'group', 'tag'), name='uniq_domain_group_tag'),
        ),
    ]
