# Generated by Django 5.2.4 on 2025-08-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewtag',
            name='category',
            field=models.CharField(choices=[('fresh', 'fresh'), ('snacks', 'snacks'), ('goods', 'goods'), ('restaurants', 'restaurants')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reviewtag',
            name='group',
            field=models.CharField(choices=[('fresh', 'fresh'), ('snacks', 'snacks'), ('goods', 'goods'), ('restaurants', 'restaurants')], max_length=50),
        ),
    ]
