# Generated by Django 5.2.4 on 2025-08-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_reviewtag_category_alter_reviewtag_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewtag',
            name='group',
            field=models.CharField(choices=[('Review Tags', 'Review Tags'), ('Dietary Restrictions', 'Dietary Restrictions'), ('Spicy Level', 'Spicy Level'), ('Freshness', 'Freshness'), ('Usefulness', 'Usefulness'), ('Portion Size', 'Portion Size')], max_length=50),
        ),
    ]
