"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

import pymysql
pymysql.install_as_MySQLdb()

import os, json
from django.core.exceptions import ImproperlyConfigured

from datetime import timedelta #login

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# secret_key setting
secret_file = os.path.join(BASE_DIR, 'secrets.json') 

with open(secret_file) as f:
    secrets = json.loads(f.read())

'''def get_secret(setting, secrets=secrets): 
# secret 변수를 가져오거나 그렇지 못 하면 예외를 반환
    try:
        return secrets[setting]
    except KeyError:
        error_msg = "Set the {} environment variable".format(setting)
        raise ImproperlyConfigured(error_msg)
'''

ENV = os.getenv('ENV', 'local')  # 기본값은 'local'

def get_secret(setting, env=ENV, secrets=secrets):
    """
    secrets.json에서 환경별 혹은 공용 변수를 가져온다.
    1. 현재 환경(LOCAL/PRODUCTION) dict 안에서 먼저 찾음
    2. 없으면 최상위 key에서 찾음
    3. 둘 다 없으면 ImproperlyConfigured 예외 발생
    """
    try:
        # 환경별 값 우선
        if env in secrets and setting in secrets[env]:
            return secrets[env][setting]
        # 환경별 값이 없으면 최상위 값
        return secrets[setting]
    except KeyError:
        error_msg = f"Set the {setting} environment variable in secrets.json"
        raise ImproperlyConfigured(error_msg)
    
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [   # 프론트 배포 후 백엔드 도메인으로 변경 
    '127.0.0.1',
    'localhost',
    'ec2-54-180-214-201.ap-northeast-2.compute.amazonaws.com',  # 퍼블릭 DNS
    '54.180.214.201',   # 퍼블릭 IPv4
]

# Application definition

DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

PROJECT_APPS = [
    'testapi',
    'accounts',
]

THIRD_PARTY_APPS = [
    "corsheaders",
    'rest_framework_simplejwt',
    # "allauth",
    # "allauth.account",
    # "allauth.socialaccount", 구글용
    # "allauth.socialaccount.providers.google", 
]

INSTALLED_APPS = DJANGO_APPS + PROJECT_APPS + THIRD_PARTY_APPS

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DB_NAME = get_secret("DB_NAME")
DB_PW = get_secret("DB_PW")

USER = get_secret("USER")
HOST = get_secret("HOST") # 로컬 테스트할 땐 'localhost'로 변경
PORT = get_secret("PORT")

# 로컬 테스트, SSH 터널링, AWS RDS 연결 바꿀 때마다 settings.py의 DB_NAME, USER, DB_PW, HOST, PORT 변경 필요
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': DB_NAME,
        'USER': USER,
        'PASSWORD': DB_PW,
        'HOST': HOST,
        'PORT': PORT,
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SECRET_KEY = get_secret("SECRET_KEY")

CORS_ALLOW_CREDENTIALS = True   

CORS_ALLOWED_ORIGINS = [    # 프론트 배포 후 프론트 도메인으로 변경
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:5173", # 프론트 - 권민정
]

### LOGIN ###

AUTH_USER_MODEL = 'accounts.User' #accounts

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

REST_USE_JWT = True

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=20),    # 유효기간 3시간 (개발 기간동안 프론트 접근 가능하도록 임의로 20일)
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),    # 유효기간 7일
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    'TOKEN_USER_CLASS': 'accounts.User',
}
