# Generated by Django 5.2.5 on 2025-08-21 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='ex',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
