# Generated by Django 5.2.5 on 2025-08-21 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menu_ex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.CharField(max_length=10),
        ),
    ]
