# Generated by Django 5.2.4 on 2025-08-19 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackTag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('polarity', models.CharField(choices=[('positive', 'positive'), ('negative', 'negative'), ('neutral', 'neutral')], default='positive', max_length=8)),
                ('tag', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('fresh', 'fresh'), ('snacks', 'snacks'), ('goods', 'goods'), ('restaurants', 'restaurants')], max_length=20)),
                ('topic', models.CharField(max_length=50)),
                ('caption', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('thumbs', models.BooleanField(default=True)),
                ('comment', models.TextField(blank=True, default='', max_length=500)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='feedbacks', to='ai.feedbacktag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
