# Generated by Django 5.2.4 on 2025-08-18 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('polarity', models.CharField(choices=[('positive', 'positive'), ('negative', 'negative')], db_index=True, default='positive', max_length=8)),
                ('tag', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('thumbs', models.BooleanField(default=True)),
                ('comment', models.TextField(blank=True, default='', max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='post', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='feedbacks', to='ai.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
