# Generated by Django 5.2.4 on 2025-08-18 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='polarity',
            field=models.CharField(choices=[('positive', 'positive'), ('negative', 'negative'), ('neutral', 'neutral')], db_index=True, default='positive', max_length=8),
        ),
    ]
