# Generated by Django 5.2.4 on 2025-08-22 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='category',
            field=models.CharField(default='goods', max_length=40),
            preserve_default=False,
        ),
    ]
