# Generated by Django 5.2.4 on 2025-08-19 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_alter_feedback_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('fresh', 'fresh'), ('snacks', 'snacks'), ('goods', 'goods'), ('restaurants', 'restaurants')], max_length=20)),
                ('topic', models.CharField(max_length=50, unique=True)),
                ('caption', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='tag',
            name='polarity',
            field=models.CharField(choices=[('positive', 'positive'), ('negative', 'negative'), ('neutral', 'neutral')], default='positive', max_length=8),
        ),
    ]
