# Generated by Django 5.2.4 on 2025-08-19 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_topic_alter_tag_polarity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='topic',
            field=models.CharField(max_length=50),
        ),
    ]
