# Generated by Django 5.2.4 on 2025-08-19 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0005_alter_topic_topic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='FeedbackTag',
        ),
    ]
