# Generated by Django 5.2.5 on 2025-08-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_url', models.URLField(max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('roadname_address', models.CharField(max_length=100)),
                ('number_address', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_uid', models.CharField(db_index=True, max_length=128)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_time', models.TimeField(blank=True, null=True)),
                ('payment_datetime', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('store_name', models.CharField(blank=True, max_length=255, null=True)),
                ('store_biz_no', models.CharField(blank=True, max_length=64, null=True)),
                ('store_address', models.TextField(blank=True)),
                ('store_tels', models.JSONField(blank=True, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('currency', models.CharField(blank=True, default='KRW', max_length=8, null=True)),
                ('receipt_result_raw', models.JSONField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['image_uid'], name='testapi_rec_image_u_43a379_idx'), models.Index(fields=['payment_date'], name='testapi_rec_payment_7b3e04_idx'), models.Index(fields=['store_name'], name='testapi_rec_store_n_30166c_idx')],
            },
        ),
    ]
