# Generated by Django 5.2.4 on 2025-08-16 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptImageReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image_uid', models.CharField(db_index=True, max_length=128)),
                ('meta_estimated_language', models.CharField(blank=True, max_length=8, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_time', models.TimeField(blank=True, null=True)),
                ('payment_datetime', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('store_name', models.CharField(blank=True, max_length=255, null=True)),
                ('store_biz_no', models.CharField(blank=True, max_length=64, null=True)),
                ('store_address', models.TextField(blank=True, null=True)),
                ('store_tels', models.JSONField(blank=True, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('currency', models.CharField(blank=True, default='KRW', max_length=8, null=True)),
                ('items_summary', models.JSONField(blank=True, null=True)),
                ('receipt_result_raw', models.JSONField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['image_uid'], name='testapi_rec_image_u_59d628_idx'), models.Index(fields=['payment_date'], name='testapi_rec_payment_2622ba_idx'), models.Index(fields=['store_name'], name='testapi_rec_store_n_b930bb_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReceiptImageReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('line_no', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('count', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='testapi.receiptimagereceipt')),
            ],
            options={
                'indexes': [models.Index(fields=['receipt'], name='testapi_rec_receipt_912a7f_idx')],
            },
        ),
    ]
