# Generated by Django 5.2.4 on 2025-08-16 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapi', '0002_receiptimagereceipt_receiptimagereceiptitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiptimagereceiptitem',
            name='receipt',
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image_uid', models.CharField(db_index=True, max_length=128)),
                ('meta_estimated_language', models.CharField(blank=True, max_length=8, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_time', models.TimeField(blank=True, null=True)),
                ('payment_datetime', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('store_name', models.CharField(blank=True, max_length=255, null=True)),
                ('store_biz_no', models.CharField(blank=True, max_length=64, null=True)),
                ('store_address', models.TextField(blank=True, null=True)),
                ('store_tels', models.JSONField(blank=True, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('currency', models.CharField(blank=True, default='KRW', max_length=8, null=True)),
                ('receipt_result_raw', models.JSONField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['image_uid'], name='testapi_rec_image_u_43a379_idx'), models.Index(fields=['payment_date'], name='testapi_rec_payment_7b3e04_idx'), models.Index(fields=['store_name'], name='testapi_rec_store_n_30166c_idx')],
            },
        ),
        migrations.DeleteModel(
            name='ReceiptImageReceipt',
        ),
        migrations.DeleteModel(
            name='ReceiptImageReceiptItem',
        ),
    ]
