# Generated by Django 5.2.4 on 2025-08-16 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapi', '0003_remove_receiptimagereceiptitem_receipt_receipt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='meta_estimated_language',
        ),
    ]
