# Generated by Django 5.2.4 on 2025-08-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapi', '0004_remove_receipt_meta_estimated_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
