# Generated by Django 5.2.4 on 2025-08-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapi', '0005_alter_receipt_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='store_address',
            field=models.TextField(blank=True),
        ),
    ]
