# Generated by Django 5.2.4 on 2025-08-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('roadname_address', models.CharField(max_length=100)),
                ('number_address', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
