# Generated by Django 5.2.5 on 2025-08-19 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.AutoField(primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=40)),
                ('category', models.CharField(default=None, max_length=40)),
                ('road_address', models.CharField(max_length=100, unique=True)),
                ('street_address', models.CharField(max_length=100, unique=True)),
                ('store_english', models.CharField(max_length=40)),
                ('store_image', models.CharField(blank=True, max_length=255, null=True)),
                ('market', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='markets.market')),
            ],
            options={
                'verbose_name': '가게',
                'verbose_name_plural': '가게 목록',
                'db_table': 'store',
            },
        ),
    ]
